language: common-lisp
sudo: false

os:
  - linux

env:
  global:
    - PATH=${HOME}/.roswell/bin:$PATH
    - ROSWELL_BRANCH=master
    - ROSWELL_INSTALL_DIR=${HOME}/.roswell
  matrix:
    - LISP=sbcl
    - LISP=ccl
install:
    - if ! $(which ros >/dev/null); then
        curl -L https://raw.githubusercontent.com/snmsts/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh;
      else
        ros -e '(ql:update-all-dists :prompt nil)';
      fi
    - ros install $LISP
    - ros install prove
cache:
  directories:
    - $HOME/.roswell
    - $HOME/.config/common-lisp
before_script:
  - ros run -- --version
  - ./autogen.sh
  - ./configure
script:
  - make
  - make tests
