language: common-lisp
sudo: false

os:
  - linux

env:
  global:
    - PATH=${HOME}/.roswell/bin:$PATH
    - ROSWELL_BRANCH=master
    - ROSWELL_INSTALL_DIR=${HOME}/.roswell
  matrix:
    - LISP=sbcl
    - LISP=ccl
install:
    - curl -L https://raw.githubusercontent.com/snmsts/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh
    - ros -e '(ql:update-all-dists :prompt nil)'
    - ros install prove
cache:
  directories:
    - $HOME/.roswell
    - $HOME/.config/common-lisp
before_script:
  - ros run -- --version
  - ros --version
  - ros config
  - ros install $LISP
  - ros use $LISP
  - ./autogen.sh
  - ./configure
script:
  - make
  - make tests
